import Foundation

/// Wispr-Flow-style tone modes, applied as a deterministic post-pass over
/// the transcript. Prompt-based style biasing would be the second half of
/// this feature (style through the middle of the text, not just the edges),
/// but WhisperKit 1.x promptTokens are broken — empty output with prefill,
/// ignored without — so post-processing is the whole mechanism for now.
enum FlowTone: String, CaseIterable, Identifiable {
    case formal, casual, veryCasual, excited

    var id: String { rawValue }

    /// Fits a keyboard chip. Lowercase on purpose — every key label on the
    /// keyboard ("space", "return", "history") follows the system keyboard's
    /// lowercase convention.
    var shortLabel: String {
        switch self {
        case .formal: "formal"
        case .casual: "casual"
        case .veryCasual: "no caps"
        case .excited: "excited!"
        }
    }

    /// Cycle order for the keyboard's tone chip.
    var next: FlowTone {
        let all = Self.allCases
        return all[(all.firstIndex(of: self)! + 1) % all.count]
    }

    var label: String {
        switch self {
        case .formal: "Formal"
        case .casual: "Casual"
        case .veryCasual: "Very casual"
        case .excited: "Excited"
        }
    }

    var detail: String {
        switch self {
        case .formal: "Full sentences. Capitalized, ends with a period."
        case .casual: "Keeps caps, drops the trailing period"
        case .veryCasual: "all lowercase, like texting"
        case .excited: "Ends with an exclamation mark!"
        }
    }

    /// The same sentence rendered in this tone — generated by the real
    /// transform, so the preview can never drift from the behavior.
    var example: String {
        apply(to: "We should meet at noon tomorrow.")
    }

    /// Deterministic style guarantees, applied after transcription.
    func apply(to text: String) -> String {
        guard !text.isEmpty else { return text }
        switch self {
        case .formal:
            var result = Self.capitalizingFirst(text)
            if !Self.hasTerminalPunctuation(result) {
                result += Self.isCJK(result) ? "。" : "."
            }
            return result
        case .casual:
            return Self.strippingTrailingPeriod(text)
        case .veryCasual:
            return Self.strippingTrailingPeriod(text).lowercased()
        case .excited:
            var result = Self.strippingTrailingPeriod(Self.capitalizingFirst(text))
            if let last = result.unicodeScalars.last, "!?！？…".unicodeScalars.contains(last) {
                return result
            }
            result += Self.isCJK(result) ? "！" : "!"
            return result
        }
    }

    // MARK: helpers

    private static func capitalizingFirst(_ text: String) -> String {
        guard let first = text.first, first.isLowercase else { return text }
        return first.uppercased() + text.dropFirst()
    }

    private static func hasTerminalPunctuation(_ text: String) -> Bool {
        guard let last = text.unicodeScalars.last else { return false }
        return ".!?。！？…".unicodeScalars.contains(last)
    }

    /// Drops a single trailing period (Latin or CJK), never an ellipsis.
    private static func strippingTrailingPeriod(_ text: String) -> String {
        guard text.hasSuffix(".") || text.hasSuffix("。"),
              !text.hasSuffix("..."), !text.hasSuffix("…") else { return text }
        return String(text.dropLast())
    }

    /// Rough script check so formal/excited endings match the text.
    private static func isCJK(_ text: String) -> Bool {
        text.unicodeScalars.reversed().first { $0.properties.isAlphabetic }
            .map { (0x2E80...0x9FFF).contains(Int($0.value)) || (0x3040...0x30FF).contains(Int($0.value)) }
            ?? false
    }
}
